"""empty message

Revision ID: 5365e8969be1
Revises: None
Create Date: 2014-11-14 15:45:26.217236

"""

# revision identifiers, used by Alembic.
revision = '5365e8969be1'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('header', postgresql.JSON(), nullable=True),
    sa.Column('rows', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('endpoint'),
    sa.UniqueConstraint('url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxies')
    ### end Alembic commands ###
